GET http://localhost:8080/api/words

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
date: Sat, 08 Mar 2025 18:56:17 GMT
connection: close
###
GET http://localhost:8080/api/languages

HTTP/1.1 200  - OK
content-type: application/json
transfer-encoding: chunked
date: Sat, 08 Mar 2025 19:25:27 GMT
connection: close
###
GET http://localhost:8080/api/examples